[package]
name = "{{ project_name }}"
version = "0.1.0"
edition = "2024"

[dependencies]
ohkami = { version = "0.24", features = ["rt_lambda"] }
lambda_runtime = "0.14"
tokio = { version = "1", features = ["macros"] }
